package models

type Video struct {
	ID          string
	Title       string
	URL         string
	Channel     ChannelInfo
	Thumbnails  []Thumbnail
	Description string

	DurationSeconds int
	IsLive          bool
	IsUpcoming      bool
	UploadedAt      string
	PublishedAt     string

	Keywords []string
	Category string

	ViewCount    int64
	LikeCount    int64
	CommentCount int64
	Rating       float32

	Formats         []Format
	AdaptiveFormats []Format

	Captions      []CaptionTrack
	Chapters      []Chapter
	Storyboards   []Storyboard
	MusicMetadata *MusicMetadata

	// Raw internal YouTube player JSON (optional debug)
	PlayerResponse map[string]any
}

type ChannelInfo struct {
	ID        string
	Name      string
	URL       string
	Thumbnail string

	SubscriberCount int64
	Verified        bool
	OfficialArtist  bool
}

type Format struct {
	Itag         int
	QualityLabel string // "1080p", "720p60", "480p", "best", etc.
	MimeType     string
	Codecs       string
	Bitrate      int

	Width         int
	Height        int
	FPS           int
	AudioQuality  string // "AUDIO_QUALITY_LOW", etc.
	AudioChannels int

	ContentLength int64
	IsHDR         bool
	IsAudioOnly   bool
	IsVideoOnly   bool

	URL     string
	Expires string
}

type Thumbnail struct {
	URL    string
	Width  int
	Height int
}

type CaptionTrack struct {
	LanguageCode  string
	LanguageName  string
	URL           string
	AutoGenerated bool
	Format        string // "vtt", "srt"
}

type Chapter struct {
	Title     string
	StartSec  int
	Thumbnail string
}

type Storyboard struct {
	URLTemplate string
	Width       int
	Height      int
	Count       int
	Rows        int
	Columns     int
	FrameSec    int
}

type MusicMetadata struct {
	Album     string
	Artist    string
	ArtistURL string
	Writers   []string
	Producers []string
	Song      string
}
